gnb ='';
gnb += '<nav id="gnb" aria-hidden="true">';
    gnb += '<a href="#btnGnb" class="btn_gnb_close">';
        gnb += '<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="32px" height="30px" viewBox="0 0 30 30" xml:space="preserve">';
            gnb += '<path class="bar b1" d="M0,22h20c0,0,9,0,9-12s-9-5-9-5L2,22"/>';
			gnb += '<path class="bar b2" d="M0,8h2h18c0,0,9,0,9,10s-5,11-11,5S2,8,2,8"/>';
			gnb += '<line class="bar b3" x1="0" y1="15" x2="20" y2="15"/>';
        gnb += '</svg>';
        gnb += '<span class="offscreen">전체메뉴 닫기</span>';
    gnb += '</a>';
gnb += '<div class="gnb_header">';
    gnb += '<div class="tit">';
        gnb += '<h2>서비스 이용을 위해<br />로그인 해주세요</h2>';
            gnb += '<ul class="btn_group grid">';
            gnb += '<li><a href="#" class="btn_login">로그인</a></li>';
            gnb += '<li><a href="#" class="btn_join">회원가입</a></li>';
        gnb += '</ul>';
    gnb += '</div>';
    gnb +='<!-- 로그인 상태 ';
    gnb +='<div class="tit">';
        gnb +='<h2><strong class="tc1">김한화</strong> 고객님,<br />오늘도 안녕하세요</h2>';
        gnb +='<ul class="btn_group grid">';
            gnb +='<li><a href="#" class="btn_join">로그아웃</a></li>';
        gnb +='</ul>';
    gnb +='</div>';
    gnb +='-->';
    gnb += '<div class="quick_menu">';
        gnb += '<ul class="grid s4">';
            gnb += '<li><a href="#" class="q1">홈</a></li>';
            gnb += '<li><a href="#" class="q2">인증센터</a></li>';
            gnb += '<li><a href="#" class="q3">MY한화</a></li>';
            gnb += '<li><a href="#" class="q4">설정</a></li>';
        gnb += '</ul>';
    gnb += '</div>';
    gnb += '<div class="my_menu">';
        gnb += '<h3>최근이용메뉴</h3>';
        gnb += '<div class="my_menu_scoller">';
            gnb += '<ul><!-- m1:계약관리, m2:보상, m3:대출, m4:보험, m5:증명서발급, m6:고객라운지, m7:스마트차도리 -->';
                gnb += '<li><a href="#" class="m1">보험계약조회</a></li>';
                gnb += '<li><a href="#" class="m2">보험금 청구</a></li>';
                gnb += '<li><a href="#" class="m3">보험계약대출 상환정보변경</a></li>';
                gnb += '<li><a href="#" class="m4">내 보험 보장분석</a></li>';
                gnb += '<li><a href="#" class="m5">보험료납입증명서 (소득공제)</a></li>';
                gnb += '<li><a href="#" class="m6">고객센터 찾기</a></li>';
                gnb += '<li><a href="#" class="m7">스마트차도리 소개</a></li>';
				gnb += '<li><a href="#" class="q1_11">보험금청구</a></li>';
				gnb += '<li><a href="#" class="q1_21">청구결과</a></li>';
				gnb += '<li><a href="#" class="q1_31">필요서류</a></li>';
				gnb += '<li><a href="#" class="q1_41">유선서류</a></li>';
				gnb += '<li><a href="#" class="q2_11">계약대출</a></li>';
				gnb += '<li><a href="#" class="q2_21">대출현황</a></li>';
				gnb += '<li><a href="#" class="q2_31">대출상환</a></li>';
				gnb += '<li><a href="#" class="q2_41">신용대출</a></li>';
				gnb += '<li><a href="#" class="q3_11">계약조회</a></li>';
				gnb += '<li><a href="#" class="q3_21">보험료납입</a></li>';
				gnb += '<li><a href="#" class="q3_31">자동이체</a></li>';
				gnb += '<li><a href="#" class="q3_41">증명서발급</a></li>';
				gnb += '<li><a href="#" class="q4_11">정보변경</a></li>';
				gnb += '<li><a href="#" class="q4_21">보장분석</a></li>';
				gnb += '<li><a href="#" class="q4_31">문의하기</a></li>';
				gnb += '<li><a href="#" class="q4_41">보이는ARS</a></li>';
            gnb += '</ul>';
        gnb += '</div>';
    gnb += '</div>';
gnb += '</div>';
gnb += '<div class="gnb_content">';
    gnb += '<div class="dep1_swipe">';
        gnb += '<ul class="swiper-wrapper">';
            gnb += '<li class="swiper-slide active"><a href="#">계약관리</a></li>';
            gnb += '<li class="swiper-slide"><a href="#">보상</a></li>';
            gnb += '<li class="swiper-slide"><a href="#">대출</a></li>';
            gnb += '<li class="swiper-slide"><a href="#">보험</a></li>';
            gnb += '<li class="swiper-slide"><a href="#">증명서발급</a></li>';
            gnb += '<li class="swiper-slide"><a href="#">고객라운지</a></li>';
            gnb += '<li class="swiper-slide"><a href="#">스마트차도리</a></li>';
        gnb += '</ul>';
    gnb += '</div>';
    gnb += '<div class="dep2_swipe">';
        gnb += '<ul class="swiper-wrapper">';
            gnb += '<li class="swiper-slide"><span class="offscreen">계약관리</span>';
                gnb += '<ul>';
                    gnb += '<li><a href="#">보험계약조회</a></li>';
                    gnb += '<li><a href="#">보험료납입</a>';
                        gnb += '<ul>';
                            gnb += '<li><a href="#" class="active">보험료납입</a></li>';
                            gnb += '<li><a href="#">효력상실예정계약 보험료납입</a></li>';
                            gnb += '<li><a href="#">보험료납입내역조회</a></li>';
                            gnb += '<li><a href="#">가상계좌발급</a></li>';
                        gnb += '</ul>';
                    gnb += '</li>';
                    gnb += '<li><a href="#">지급/환급</a>';
                        gnb += '<ul>';
                            gnb += '<li><a href="#">중도인출금조회/신청</a></li>';
                            gnb += '<li><a href="#">중도환급금조회/신청</a></li>';
                            gnb += '<li><a href="#">만기환급금조회/신청</a></li>';
                            gnb += '<li><a href="#">휴면보험금조회/신청</a></li>';
                            gnb += '<li><a href="#">환급금수령계좌변경</a></li>';
                        gnb += '</ul>';
                    gnb += '</li>';
                    gnb += '<li><a href="#">보험계약변경</a>';
                        gnb += '<ul>';
                            gnb += '<li><a href="#">자동이체신청변경</a></li>';
                            gnb += '<li><a href="#">보험소재지변경</a></li>';
                            gnb += '<li><a href="#">태아보험자녀등록</a></li>';
                        gnb += '</ul>';
                    gnb += '</li>';
                    gnb += '<li><a href="#">고객정보변경</a>';
                        gnb += '<ul>';
                            gnb += '<li><a href="#">주소/연락처/이메일변경</a></li>';
                            gnb += '<li><a href="#">우편물수령처변경</a></li>';
                        gnb += '</ul>';
                    gnb += '</li>';
                    gnb += '<li><a href="#">완전판매모니터링</a></li>';
                gnb += '</ul>';
            gnb += '</li>';
            gnb += '<li class="swiper-slide"><span class="offscreen">보상</span>';
                gnb += '<ul>';
                    gnb += '<li><a href="#">보험금 청구</a></li>';
                    gnb += '<li><a href="#">보험금 청구결과조회</a></li>';
                    gnb += '<li><a href="#">유선서류제출</a></li>';
                    gnb += '<li><a href="#">보험금 청구서신청</a></li>';
                    gnb += '<li><a href="#">필요서류안내</a></li>';
                    gnb += '<li><a href="#">장기보험금 청구절차</a></li>';
                gnb += '</ul>';
            gnb += '</li>';
            gnb += '<li class="swiper-slide"><span class="offscreen">대출</span>';
                gnb += '<ul>';
                    gnb += '<li><a href="#">대출현황조회</a></li>';
                    gnb += '<li><a href="#">보험계약대출신청</a></li>';
                    gnb += '<li><a href="#">보험계약대출상환</a></li>';
                    gnb += '<li><a href="#">보험계약대출상환정보변경</a></li>';
                    gnb += '<li><a href="#">신용대출상환</a></li>';
                gnb += '</ul>';
            gnb += '</li>';
            gnb += '<li class="swiper-slide"><span class="offscreen">보험</span>';
                gnb += '<ul>';
                        gnb += '<li><a href="#">내 보험 보장분석</a></li>';
                        gnb += '<li><a href="#">모바일바로가입</a>';
                            gnb += '<ul>';
                                gnb += '<li><a href="#">한화다이렉트자동차보험</a></li>';
                                gnb += '<li><a href="#">한화다이렉트포켓암보험</a></li>';
                                gnb += '<li><a href="#">OK2500든든운전자보험</a></li>';
                                gnb += '<li><a href="#">LIFEPLUS 맘더한어린이보험</a></li>';
                            gnb += '</ul>';
                        gnb += '</li>';
                        gnb += '<li><a href="#">자동차보험</a>';
                            gnb += '<ul>';    
                                gnb += '<li><a href="#">한화개인용자동차보험</a></li>';
                                gnb += '<li><a href="#">ECO마일리지 할인형 특약</a></li>';
                                gnb += '<li><a href="#">ECO마일리지 특약 후정산</a></li>';
                                gnb += '<li><a href="#">전방충돌방지장치 특약</a></li>';
                                gnb += '<li><a href="#">차선이탈경고장치 특약</a></li>';
                            gnb += '</ul>';
                        gnb += '</li>';
                        gnb += '<li><a href="#">운전자보험</a>';
                            gnb += '<ul>';
                                gnb += '<li><a href="#">차도리운전자보험</a></li>';
                                gnb += '<li><a href="#">차도리ECO운전자상해보험</a></li>';
                            gnb += '</ul>';
                        gnb += '</li>';
                        gnb += '<li><a href="#">건강/종합보험</a>';
                            gnb += '<ul>';
                                gnb += '<li><a href="#">마이라이프투모로종합보험</a></li>';
                                gnb += '<li><a href="#">마이라이프한아름종합보험</a></li>';
                                gnb += '<li><a href="#">마이라이프굿밸런스건강보험</a></li>';
                                gnb += '<li><a href="#">마이라이프플러스종합보험</a></li>';
                                gnb += '<li><a href="#">실속더한든든보장보험</a></li>';
                                gnb += '<li><a href="#">한화한아름간병보험</a></li>';
                                gnb += '<li><a href="#">하얀미소플러스치아보험Ⅱ</a></li>';
                                gnb += '<li><a href="#">한화실손의료보험(갱신형)Ⅱ</a></li>';
                                gnb += '<li><a href="#">실속더한든든암보험</a></li>';
                                gnb += '<li><a href="#">참편한실속암보험</a></li>';
                                gnb += '<li><a href="#">참편한실손의료보험(간편고지, 갱신형)</a></li>';
                                gnb += '<li><a href="#">한화노후실손의료보험(갱신형)</a></li>';
                                gnb += '<li><a href="#">참편한건강보험(연만기갱신형)</a></li>';
                                gnb += '<li><a href="#">참편한실속건강보험</a></li>';
                            gnb += '</ul>';
                        gnb += '</li>';
                        gnb += '<li><a href="#">가족보험</a>';
                            gnb += '<ul>';
                                gnb += '<li><a href="#">1등엄마의똑똑한자녀보험</a></li>';
                                gnb += '<li><a href="#">세이프투게더생활종합보험</a></li>';
                                gnb += '<li><a href="#">실속더한든든자녀보험</a></li>';
                            gnb += '</ul>';
                        gnb += '</li>';
                        gnb += '<li><a href="#">화재/재물보험</a>';
                            gnb += '<ul>';
                                gnb += '<li><a href="#">한화BIG PLUS재산종합보험</a></li>';
                                    gnb += '</ul>';
                                gnb += '</li>';
                                gnb += '<li><a href="#">여행/레저보험</a>';
                                    gnb += '<ul>';    
                                        gnb += '<li><a href="#">해외유학생보험</a></li>'; 
                                    gnb += '</ul>';
                                gnb += '</li>';
                                gnb += '<li><a href="#">연금/저축보험</a>';
                                    gnb += '<ul>';    
                                        gnb += '<li><a href="#">골드연금보험</a></li>';
                                        gnb += '<li><a href="#">드림모아저축보험</a></li>';
                                    gnb += '</ul>';
                                gnb += '</li>';
                                gnb += '<li><a href="#">기업보험</a>';
                                    gnb += '<ul>';
                                        gnb += '<li><a href="#">재난배상책임보험</a></li>';
                                    gnb += '</ul>';
                                gnb += '</li>';
                            gnb += '</ul>';
                        gnb += '</li>';
                        gnb += '<li class="swiper-slide"><span class="offscreen">증명서발급</span>';
                            gnb += '<ul>';
                                gnb += '<li><a href="#">보험료납입증명서(소득공제)</a></li>';
                                gnb += '<li><a href="#">장기보험</a></li>';
                                gnb += '<li><a href="#">일반보험(여행자보험)</a></li>';
                                gnb += '<li><a href="#">장기보상</a></li>';
                                gnb += '<li><a href="#">대출</a></li>';
                                gnb += '<li><a href="#">부채잔액증명서</a></li>';
                                gnb += '<li><a href="#">필요서류다운로드</a></li>';
                            gnb += '</ul>';
                        gnb += '</li>';
                        gnb += '<li class="swiper-slide"><span class="offscreen">고객라운지</span>';
                            gnb += '<ul>';
                                gnb += '<li><a href="#">공지사항</a></li>';
                                gnb += '<li><a href="#">이벤트</a></li>';
                                gnb += '<li><a href="#">자주하는 질문</a></li>';
                                gnb += '<li><a href="#">1:1 문의하기</a></li>';
                                gnb += '<li><a href="#">ARS 이용안내</a></li>';
                                gnb += '<li><a href="#">고객센터/지점/보상센터 찾기</a></li>';
                                gnb += '<li><a href="#">공식 SNS 채널</a>';
                                    gnb += '<ul>';
                                        gnb += '<li><a href="#">페이스북 페이지</a></li>';
                                        gnb += '<li><a href="#">차도리 블로그</a></li>';
                                        gnb += '<li><a href="#">하얀미소 블로그</a></li>';
                                    gnb += '</ul>';
                                gnb += '</li>';
                            gnb += '</ul>';
                        gnb += '</li>';
                        gnb += '<li class="swiper-slide"><span class="offscreen">스마트차도리</span>';
                            gnb += '<ul>';
                                gnb += '<li><a href="#">스마트차도리 소개</a></li>';
                                gnb += '<li><a href="#">보험관리</a>';  
                            gnb += '<ul>';
                                gnb += '<li><a href="#">마일리지 (주행거리관리)</a></li>';
                                gnb += '<li><a href="#">계약 조회</a></li>';
                                gnb += '<li><a href="#">계약변경내역 조회</a></li>';
                                gnb += '<li><a href="#">단기운전자 변경</a></li>';
                                gnb += '<li><a href="#">자동차번호 변경</a></li>';
                                gnb += '<li><a href="#">운전자특약 변경</a></li>';
                                gnb += '<li><a href="#">자동차 변경 (차량대체)</a></li>';
                                gnb += '<li><a href="#">가입경력인정자 신청</a></li>';
                                gnb += '<li><a href="#">담보가입금액 변경</a></li>';
                                gnb += '<li><a href="#">갱신예약서비스</a></li>';
                            gnb += '</ul>';
                        gnb += '</li>';
                        gnb += '<li><a href="#">증명서발급</a></li>';
                        gnb += '<li><a href="#">사진증빙</a></li>';
                        gnb += '<li><a href="#">케어서비스</a>';
                            gnb += '<ul>';
                                gnb += '<li><a href="#">긴급출동</a></li>';
                                gnb += '<li><a href="#">사고접수</a></li>';
                                gnb += '<li><a href="#">AI수리견적</a></li>';
                                gnb += '<li><a href="#">안전지킴이</a></li>';
                                gnb += '<li><a href="#">사고알림이</a></li>';
                            gnb += '</ul>';
                        gnb += '</li>';
                        gnb += '<li><a href="#">매거진</a>';
                            gnb += '<ul>';
                                gnb += '<li><a href="#">매거진</a></li>';
                                gnb += '<li><a href="#">이벤트</a></li>';
                            gnb += '</ul>';
                        gnb += '</li>';
                        gnb += '<li><a href="#">차도리TALK</a></li>';
                    gnb += '</ul>';
                gnb += '</li>';
            gnb += '</ul>';
			gnb += '<div class="swipe_guide"></div>';
        gnb += '</div>';
    gnb += '</div>';
gnb += '</nav>';

document.write(gnb);